DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS Authority;
DROP TABLE IF EXISTS  AUTHORITIES;

CREATE TABLE user
(
  id BIGINT(20) NOT NULL COMMENT '主键ID',
  name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
  username VARCHAR(30) NULL DEFAULT NULL COMMENT '登入名',
  password VARCHAR(255) NULL DEFAULT NULL COMMENT '密码',
  enable bit(1) NULL DEFAULT NULL COMMENT '是否启用',
  age INT(11) NULL DEFAULT NULL COMMENT '年龄',
  email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
  PRIMARY KEY (id)
);

CREATE TABLE Authority
(
  id BIGINT(20) NOT NULL COMMENT '主键ID',
  userId BIGINT(20) NULL DEFAULT NULL COMMENT '用户id',
  Authority VARCHAR(30) NULL DEFAULT NULL COMMENT '权限',
  PRIMARY KEY (id)
);