server:
  port: 8000
mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  application:
    name: spring-boot-main
  datasource:
    username: root
    password: abc123
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
feign:
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 10000