server:
  port: 8000
management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: gate-service
  profiles:
    active: dev
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: ${spring.cloud.client.ip-address}
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s
        ip-address: true
        instance-id: ${spring.application.name}:${spring.cloud.client.ipaddress}:${server.port}
        tags: ${spring.profiles.active}
        service-name: ${spring.application.name}

    gateway:
      discovery:
        locator:
          # 是否启用默认转发规则  规则 ->/服务名/请求路径
          enabled: true
          # 默认服务名不改成大写
          lowerCaseServiceId: true
      routes:
        # /web/**的都转发到web-service 并去掉/web前缀
        - id: web-service
          uri: lb://web-service
          predicates:
            - Path=/web/**
          filters:
            - StripPrefix=1
