#spring:
#cloud:
#gateway:
# 配置路由信息
#routes:
# id是每个路由规则的唯一id
#- id after_router
#  uri: http://127.0.0.0:803
# 筛选器【启用条件】
#  predicates:
# 指定时间内转发到127.0.0.1
#- After=2017-01-20T17:42:47.789-07:00[America/Denver]
# 必须带token 否则404
#- Cookie=name, token
#host值不符合则返回404
#- Host=**.coderstory.cn
# GET请求都会转发到127.0.0.1
#- Method=GET
#根据路径匹配转发到127.0.0.1
#- Path=/user/home
# 更具请求参数转发 value可不写
#- Query=name, coderstory
#filters:
# 过滤器 添加header
#- AddRequestHeader=X-Request-Foo, Bar
# 路径重写 /foo/**都 重写成/** 转发到127.0.0.1
#- RewritePath=/foo/(?<segment>.*),/$\{segment}

#profiles: after_router