server:
  port: 8741
mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  profiles:
    active: dev
  application:
    name: web-service
  datasource:
    username: root
    password: abc123
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
feign:
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 10000