server:
  port: 8001
spring:
  datasource:
    username: rc_dev_all
    password: 6TjKFG9M746S
    url: jdbc:mysql://172.16.10.244:3306/rc_dev_cust_test_data?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC