# Configuration for actuator
# Access url :  http://127.0.0.14:8002/actuator
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500

