server:
  port: 8002
mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  profiles:
    active: dev
  application:
    name: web-service
  datasource:
    username: rc_dev_all
    password: 6TjKFG9M746S
    url: jdbc:mysql://172.16.10.244:3306/rc_dev_cust_test_data?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: ${spring.cloud.client.ip-address}
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s
        ip-address: true
        instanceId: ${spring.application.name}:${spring.cloud.client.ipaddress}:${server.port}
        tags: ${spring.profiles.active}
        service-name: ${spring.application.name}
feign:
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 10000
