server:
  port: 8003
spring:
  application:
    name: zuul-service
zuul:
  routes:
    home:
      path: /home/**
      serviceId: web
    user:
      path: /user/**
      serviceId: user-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/